=== piggsoft/redis-piggsoft/src/main/resources/redis.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.piggsoft.com/redis"
           targetNamespace="http://www.piggsoft.com/redis"
           elementFormDefault="qualified">

    <xs:element name="configuration" type="config"/>

    <xs:element name="host" type="host"/>

    <xs:complexType name="config">
        <xs:sequence>
            <xs:element name="isSharding" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="isCluster" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="maxTotal" type="xs:int" minOccurs="0" maxOccurs="1"/>
            <xs:element name="maxIdle" type="xs:int" minOccurs="0" maxOccurs="1"/>
            <xs:element name="maxWaitMillis" type="xs:long" minOccurs="0" maxOccurs="1"/>
            <xs:element name="testOnBorrow" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="minIdle" type="xs:int" minOccurs="0" maxOccurs="1"/>
            <xs:element name="hosts" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="host" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="host">
        <xs:sequence>
            <xs:element name="url" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="port" type="xs:int" minOccurs="0" maxOccurs="1"/>
            <xs:element name="timeout" type="xs:int" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== piggsoft/redis-piggsoft/src/test/resources/redis.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration
        xmlns="http://www.piggsoft.com/redis"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.piggsoft.com/redis http://www.piggsoft.com/redis.xsd">
    <!--是否是分片-->
    <isSharding>true</isSharding>
    <!--是否是集群， 集群和分片只能有一个为true，但都可为false-->
    <isCluster>false</isCluster>
    <hosts>
        <host>
            <url>172.16.16.185</url>
            <port>6379</port>
        </host>
        <host>
            <url>172.31.3.38</url>
            <port>6379</port>
        </host>
    </hosts>
</configuration>
